name: MakeCode

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g pxt
          pxt target arcade
      - name: build
        run: |
          pxt install
          pxt build --cloud
        env:
          CI: true

  check-cfg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g pxt
          pxt target arcade
      - name: Fix files listed in config if necessary
        run: node ./.github/workflows/json-check.js
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'missing files listed in pxt.json'
          commit-message: 'Removing missing files from pxt.json'
